import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "portfolio next/sanity",
  description: "Generated by create next app"
};

import { SanityLive } from "@/sanity/lib/live";

export default function FrontendLayout({
  children
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <>
      {children}
      <SanityLive />
    </>
  );
}
