import { draftMode } from "next/headers";
import { VisualEditing } from "next-sanity";
import { DisableDraftMode } from "@/components/DisableDraftMode";

import Header from "@/components/Header";
import { SanityLive } from "@/sanity/lib/live";
import type { Metadata } from "next";
import "./../globals.css";

import { Inter } from "next/font/google";

export const metadata: Metadata = {
  title: "portfolio next/sanity",
  description: "Generated by create next app"
};

const inter = Inter({
  variable: "--font-inter",
  subsets: ["latin"],
  display: "swap"
});

export default async function FrontendLayout({
  children
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <section className={`${inter.variable} bg-white text-black pt-24`}>
      <Header />
      <main className="">
        {children}
        <SanityLive />
        {(await draftMode()).isEnabled && (
          <>
            <DisableDraftMode />
            <VisualEditing />
          </>
        )}
      </main>
    </section>

    // <section className="bg-white min-h-screen">
    //   <Header />
    //   {children}
    //   <SanityLive />
    // </section>
  );
}
